### ISSUE TITLE
Run only one script

### ISSUE THREAD

**Issue by ThiagoMiranda** [babel/example-node-server#23]
Hi!

I'm deploying my app in a elastic bean instance so basically I have the option to run just one script.
If I try to run something like:
```
"start": "npm run build & node script.js"
```
it's not guaranteed that the first one has finished before the second one starts. Is there an way to pass through that? 

Ps: I'm using eb deploy from ElasticBean

Thanks

**Comment by ThiagoMiranda** [comment]
I think I got it using hooks.
Basically I have a `prestart` that builds the application. Dunno if this is the best approach though.

Thanks =)

**Comment by antonsamper** [comment]
@ThiagoMiranda i have the same steps with my apps but i ran `npm run build` before i deploy to AWS. Essentially, the files that are deployed are the final ones, the built ones, so then I only have to run `npm start` on Elastic Beanstalk.

**Comment by ThiagoMiranda** [comment]
@antonsamper I'm sorry for the dumb question but how do you do it? Does your "dist" folder is on .gitignore? Do you still use `eb deploy`?
I'm a little new on EB so I thought that `eb deploy` would "clone" and zip your whole repository to the aws machine.

**Comment by antonsamper** [comment]
Hi @ThiagoMiranda, I dont use `eb deploy`, I have a slightly different workflow setup on CircleCI that uses the `aws elasticbeanstalk` cli.

With my workflow, I generate the code that will be deployed by running `npm run build`. That creates my `dist` folder (which is in `.gitignored`). I then upload the `dist` and `package.json` to S3 (zipped up) and I then run `aws elasticbeanstalk..... [options..]` to tell Beanstalk that theres a new application that needs to be deployed.

By default, when a new application is deployed to Beanstalk, `npm i --production` will run as part of the application setup so you definitely don't have to include `node_modules` in your application zip.

I've just been reading and looks like `eb deploy` uses the last commit as the source. This is ok but it depends on what your project/workflow is. For instance, if you're using babel, then you would have to also commit your dist folder, otherwise your code wont be compiled.

My workflow is more fine tuned so i wouldnt be able to use `eb deploy`. Have a look at the links below and see if they help.

References:
* http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-deploy.html
* http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html#eb-cli3-artifact
* http://docs.aws.amazon.com/cli/latest/reference/elasticbeanstalk/create-application.html

**Comment by ThiagoMiranda** [comment]
@antonsamper thanks a lot. I'll dig into it.

**Comment by myrcutio** [comment]
not sure if you solved it or not, but the single `&` tells bash to run commands in parallel.  if you specify `&&` it forces it to run in sequence.
